[package]
name = "navis-unpol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Unpolarized single-inclusive hadron production matrix elements and PDF/FF interface"
license.workspace = true

[dependencies]
navis-core = { workspace = true }
neopdf = { workspace = true }
pineappl = { workspace = true }
